### PR TITLE
Minor improvements on README.md

### PR DESCRIPTION
**Pull request by ebraminio**
Hi. Here is some minor improvements I thought would be useful for the work. I hope you will find it useful also. Thanks for this nice work :)

### CODE REVIEW

**Comment by eek** [comment]
Haha, awesome, did you used it? 😁 

We have some improvements on the pipeline, but those will come later this year 😱

**Comment by ebraminio** [comment]
Yes, took few days to do so. Nice, would there any schema change? Looking forward to those also anyways :)

**Comment by legraphista** [comment]
No schema changes are in plan, but rather optimising the import times. Using cypher is a bit slow on the relationship side and you cannot dynamically set relationship types, a complete rewrite using [apoc](https://github.com/neo4j-contrib/neo4j-apoc-procedures) should speed up a lot of things.

**Comment by ebraminio** [comment]
Sounds fantastic!

**Pull request merged**
